### ISSUE TITLE
Publishing GitHub packages

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#748]
Currently, we are not publishing GitHub packages. [They allow convenient access to the library](https://github.com/TobseF/HelloMaven).

**Reference**: [Publishing Java packages with Gradle](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle): *You can use Gradle to publish Java packages to a registry as part of your continuous integration (CI) workflow.* See specifically [publishing packages to GitHub packages](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages).

The process seemingly succeeds 

https://github.com/RoaringBitmap/RoaringBitmap/actions/runs/11467971844

but we cannot see any package.

Help is invited.

We have added the following workflow which should publish GitHub packages when we issue a new release...

```yml
name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Our gradle configuration...

```kotlin

plugins {
    id("maven-publish")
}


subprojects {
    apply(plugin = "java-library")
    apply(plugin = "maven-publish")
    publishing {
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/RoaringBitmap/RoaringBitmap")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
```

Please see also https://github.com/RoaringBitmap/RoaringBitmap/issues/749

**Comment by billywhizz** [comment]
i don't know anything about gradle's github integration, but you could just upload the artifacts yourself.

e.g.

https://github.com/just-js/lo/blob/main/.github/workflows/release.yml#L36


```yaml
      - name: upload compressed artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lo-mac-${{ matrix.platform }}.gz
          asset_name: lo-mac-${{ matrix.platform }}.gz
          asset_content_type: application/gzip
```
